In [2]:
import numpy

arr15 = numpy.arange(1, 10)

print(arr15)

[1 2 3 4 5 6 7 8 9]


In [3]:
#soma:
numpy.sum(arr15)

45

In [4]:
#produto
numpy.prod(arr15)

362880

In [5]:
#soma acumulada
numpy.cumsum(arr15)

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45])

In [6]:
#soma de arrays
arr16 = numpy.array([3, 2, 1])
arr17 = numpy.array([1, 2, 3])

arr18 = numpy.add(arr16, arr17)

print(arr18)

[4 4 4]


In [7]:
#multiplicar elementos de matrizes
arr19 = numpy.array([[1, 2], [3, 4]])
arr20 = numpy.array([[5, 6], [0, 7]])

arr21 = numpy.dot(arr19, arr20)

In [8]:
print(arr21)

[[ 5 20]
 [15 46]]


In [9]:
#outra maneira de multiplicar matrizes
arr21 = arr19 @ arr20

In [10]:
print(arr21)

[[ 5 20]
 [15 46]]
