In [1]:
import numpy

arr22 = numpy.diag(numpy.arange(3))

In [2]:
print(arr22)

[[0 0 0]
 [0 1 0]
 [0 0 2]]


In [3]:
#comparação item a item

a = numpy.array([1, 2, 3, 4])
b = numpy.array([4, 2, 2, 4])

In [4]:
a == b

array([False,  True, False,  True])

In [5]:
#comparação global

numpy.array_equal(a, b)

False

In [7]:
#somando um valor a cada elemento do array

numpy.array([1, 2, 3]) + 1.5

array([2.5, 3.5, 4.5])

In [9]:
arr24 = numpy.array([1.2, 1.5, 1.6, 2.5, 3.5, 4.5])

In [11]:
#arredondando os valores do array

arr25 = numpy.around(arr24)

In [12]:
print(arr25)

[1. 2. 2. 2. 4. 4.]


In [14]:
#método flatten
#convertendo um objeto bidimensional em um unidimensional

arr26 = numpy.array([[1, 2, 3, 4], [5, 6, 7, 8]])

In [15]:
arr27 = arr26.flatten()

In [16]:
print(arr27)

[1 2 3 4 5 6 7 8]


In [17]:
arr28 = numpy.array([1, 2, 3])

#repete os elementos do array
numpy.repeat(arr28, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [18]:
#repete a combinação inteira do array
numpy.tile(arr28, 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [19]:
arr29 = numpy.array([1, 2])

In [20]:
arr30 = numpy.copy(arr29)

In [21]:
print(arr30)

[1 2]
